apiVersion: v1
kind: Service
metadata:
  name: quickstart-es-http-external
  namespace: development
spec:
  type: NodePort
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: quickstart
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    nodePort: 30000 # Example NodePort, this will be accessible from the outside
