apiVersion: v1
kind: Service
metadata:
  name: recipe-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: recipe-web-app
  ports:
    - protocol: TCP
      port: 880
      targetPort: 80

