apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-client
  template:
    metadata:
      labels:
        app: mongo-client
    spec:
      containers:
      - name: mongo-client
        image: mongo:latest
        command:
        - sleep
        - "3600"
